"""
train_model.py — 逻辑回归训练：空车 vs 有人

Step 1: 特征提取 + 标签
Step 2: 标准化 + 训练 LogisticRegression
Step 3: 评估 + 导出 C 权重头文件
"""

import sys, csv, os
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

# ─── 特征选择：基于之前 cir_compare 分析里区分度最高的 bin ───
#   bin 2, 25, 63, 69, 8 — FFT 分析 top hits
#   bin 31, 103 — 相位方差变化大的
#   全局特征：fp_power, noise, mag_mean_all

SELECTED_BINS = [2, 8, 25, 31, 63, 69, 103]    # 7 个区分度最高的 bin
N_FEAT_PER_BIN = 2   # 幅度 + 相位（瞬时值）

def load_csv(filepath, label):
    """返回 features[n_frames][n_features], labels[n_frames]"""
    rows, tstamps = [], []
    with open(filepath, encoding='utf-8', errors='replace') as f:
        for row in csv.reader(f):
            if row and row[0].lstrip('-').isdigit():
                vals = []
                for v in row:
                    try: vals.append(float(v))
                    except: pass
                if len(vals) >= 7:
                    tstamps.append(vals[0])
                    rows.append(vals[1:])

    data = np.array(rows, dtype=np.float64)
    n_bins = max(4, (data.shape[1] - 5) // 2)

    n_frames = data.shape[0]
    n_feat = len(SELECTED_BINS) * N_FEAT_PER_BIN + 4  # +4 = fp_power, noise, mag_mean, mag_std
    features = np.zeros((n_frames, n_feat), dtype=np.float32)

    # ── 全局特征 ──
    # fp_power = col index 3 (data row = [seq, fp, rxp, fpp, noise, I/Q...])
    features[:, 0] = data[:, 3]   # fp_power (首径功率)
    features[:, 1] = data[:, 4]   # noise (前20bin噪声均值)

    # 全局幅度均值 & 标准差
    for i in range(n_frames):
        mags = []
        for j in range(n_bins):
            i_col = 5 + j * 2
            q_col = 5 + j * 2 + 1
            if q_col < data.shape[1]:
                mags.append(np.sqrt(data[i, i_col]**2 + data[i, q_col]**2))
        mags = np.array(mags)
        features[i, 2] = np.mean(mags)
        features[i, 3] = np.std(mags)

    # ── 逐 bin 特征 ──
    for k, bin_j in enumerate(SELECTED_BINS):
        if bin_j < n_bins:
            i_col = 5 + bin_j * 2
            q_col = 5 + bin_j * 2 + 1
            if q_col < data.shape[1]:
                # 幅度
                mag = np.sqrt(data[:, i_col]**2 + data[:, q_col]**2)
                features[:, 4 + k*2] = mag
                # 相位
                features[:, 4 + k*2 + 1] = np.arctan2(data[:, q_col], data[:, i_col])

    labels = np.full(n_frames, label, dtype=np.int32)
    return features, labels, n_frames

def feature_names():
    names = ["fp_power", "noise", "mag_mean", "mag_std"]
    for b in SELECTED_BINS:
        names += [f"bin{b}_mag", f"bin{b}_phase"]
    return names

# ─── Main ───
def main():
    if len(sys.argv) < 3:
        print("Usage: python train_model.py <empty.csv> <human.csv>")
        sys.exit(1)

    print(f"Loading data...")
    X0, y0, n0 = load_csv(sys.argv[1], 0)  # empty
    X1, y1, n1 = load_csv(sys.argv[2], 1)  # human
    print(f"  Empty: {n0} frames  |  Human: {n1} frames  |  Features: {X0.shape[1]}")

    X = np.vstack([X0, X1])
    y = np.hstack([y0, y1])

    # 防止 NaN（除以零等）
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

    # ── 标准化 ──
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # ── 训练/测试分割 ──
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=42, stratify=y)

    # ── 训练 ──
    model = LogisticRegression(C=1.0, max_iter=1000, solver='lbfgs')
    model.fit(X_train, y_train)

    # ── 评估 ──
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred, pos_label=1)
    cm  = confusion_matrix(y_test, y_pred)

    print(f"\n{'='*55}")
    print(f"  TRAINING RESULTS")
    print(f"{'='*55}")
    print(f"  Accuracy:  {acc*100:.1f}%")
    print(f"  Recall:    {rec*100:.1f}%  (human detected)")
    print(f"  Confusion Matrix:")
    print(f"              Pred Empty  Pred Human")
    print(f"  True Empty     {cm[0,0]:5d}       {cm[0,1]:5d}")
    print(f"  True Human     {cm[1,0]:5d}       {cm[1,1]:5d}")

    # ── 导出 C 头文件 ──
    W = model.coef_.flatten()
    b = model.intercept_[0]
    mu = scaler.mean_
    sigma = scaler.scale_

    nf = len(W)
    names = feature_names()

    out_path = os.path.join(os.path.dirname(__file__) or '.', 'model_weights.h')
    with open(out_path, 'w') as f:
        f.write("/* Auto-generated by train_model.py — DO NOT EDIT */\n")
        f.write(f"#define ML_N_FEAT {nf}\n\n")
        f.write(f"static const float ml_W[{nf}] = {{\n    ")
        for i, v in enumerate(W):
            f.write(f"{v:.8f}f")
            if i < nf-1: f.write(", ")
            if (i+1) % 6 == 0: f.write("\n    ")
        f.write("\n};\n\n")
        f.write(f"static const float ml_b = {b:.8f}f;\n\n")
        f.write(f"static const float ml_mu[{nf}] = {{\n    ")
        for i, v in enumerate(mu):
            f.write(f"{v:.6f}f")
            if i < nf-1: f.write(", ")
            if (i+1) % 6 == 0: f.write("\n    ")
        f.write("\n};\n\n")
        f.write(f"static const float ml_sigma[{nf}] = {{\n    ")
        for i, v in enumerate(sigma):
            f.write(f"{v:.6f}f")
            if i < nf-1: f.write(", ")
            if (i+1) % 6 == 0: f.write("\n    ")
        f.write("\n};\n")
    print(f"\n  Weights exported: {out_path}")

    # ── 特征重要性 ──
    print(f"\n  Feature importance (|W| × sigma_range):")
    importance = np.abs(W[:nf])
    idx = np.argsort(-importance)
    for i in idx[:10]:
        print(f"    {names[i]:>14s}  |W|={importance[i]:.3f}")

if __name__ == "__main__":
    main()
